networks:
  coolify:
    external: true

services:
  caddy:
    build:
      context: .
      dockerfile: apps/app/Dockerfile
      target: release
    container_name: coolify-proxy
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - CADDY_DOCKER_POLLING_INTERVAL=5s
      - CADDY_DOCKER_CADDYFILE_PATH=/dynamic/Caddyfile
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    labels:
      - coolify.managed=true
      - coolify.proxy=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
#      - '/data/coolify/proxy/caddy/dynamic:/dynamic'
      - '/data/coolify/proxy/caddy/config:/config'
      - '/data/coolify/proxy/caddy/data:/data'
      - "./apps/app/Caddyfile:/dynamic/app.caddy:ro"
